# volumes:
volumes:
  jwtdown-db-data:
    external: true

  mongo-data:
    external: true

services:
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: PTB
      MONGO_INITDB_ROOT_PASSWORD: seedling

  fastapi:
    environment:
      SIGNING_KEY: 33ac8d0fd56acf48694be359dfdfb29cd0d31ec0ff22f4f491548440eba29d22f9e01110e8e7781b287b9d36849f49d4ecf83c83ba498c8fb9b6480b76f82ceb
      CORS_HOST: http://localhost:3000
      DATABASE_URL: mongodb://PTB:seedling@mongo:27017/
      DB_NAME: db-seedling-db
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
